# ????
server:
  port: 9090
  tomcat:
    uri-encoding: utf-8

spring:
  kafka:
    bootstrap-servers: 47.100.200.104:9092
    topic: test-topic
    # ?????
    producer:
      # ack??????? 1 ??????? leader ????
      acks: 1
      # ??????? Integer. MAX_VALUE
      retries: 3
      # ???????????16K?
      batch-size: 16384
      # ??????????(32M)
      buffer-memory: 33554432
      # key ? value??????????????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # ?????
    consumer:
      group-id: comsumer
      enable-auto-commit: false
      # earliest???????   latest?????????   ??latest
      auto-offset-reset: latest
      # key?value??????????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    # ?????
    listener:
      # ???????
      concurrency: 6
      # ??????????????ackMode
      ack-mode: MANUAL

