server:
  port: 9090

spring:
  shardingsphere:
    # 将运行模式配置为 Standalone 单机模式（Cluster：集群模式）
    mode:
      type: Standalone
      repository:
        type: JDBC

    datasource:
      names: ds0
      # 配置第一个数据源
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.231.6.21:3306/test_db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: budai#123456

    # 执行时显示SQL语句
    props:
      # 日志显示具体的SQL
      sql-show: true

    # 配置分片规则
    rules:
      # 配置分片策略
      sharding:
        # 配置所有分片表
        tables:
          # 配置表名
          user_info:
            # 声明表所在的数据节点
            actual-data-nodes: ds0.user_info_$->{1..2}

            # 配置分表规则
            table-strategy:
              standard:
                # 配置分表的路由键
                sharding-column: name
                # 策略算法名称
                sharding-algorithm-name: user-inline

        # 定义分片算法
        sharding-algorithms:
          user-inline:
            # 使用自定义表达式
            type: inline
            props:
              algorithm-expression: user_info_$->{(id % 2) == 0 ? 2:1}
          user-hash:
            # 使用内置的哈希算法
            type: HASH_MOD
            props:
              sharding-count: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
