server:
  port: 9090

spring:
  datasource:
    # oracle: oracle.jdbc.driver.OracleDriver
    # postgres: org.postgresql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.231.6.65:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5
      max-active: 30
      min-idle: 10
      max-wait: 6000
      web-stat-filter.enabled: true
      stat-view-servlet.enabled: true


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl